export type OrderType =
  | "rank-boost"
  | "placement-matches"
  | "net-wins"
  | "custom-request";
export type RankType =
  | "Iron IV"
  | "Iron III"
  | "Iron II"
  | "Iron I"
  | "Bronze IV"
  | "Bronze III"
  | "Bronze II"
  | "Bronze I"
  | "Silver IV"
  | "Silver III"
  | "Silver II"
  | "Silver I"
  | "Gold IV"
  | "Gold III"
  | "Gold II"
  | "Gold I"
  | "Platinum IV"
  | "Platinum III"
  | "Platinum II"
  | "Platinum I"
  | "Diamond IV"
  | "Diamond III"
  | "Diamond II"
  | "Diamond I"
  | "Master"
  | "Grandmaster"
  | "Challenger"
  | "Emerald IV"
  | "Emerald III"
  | "Emerald II"
  | "Emerald I";
export type QueueType = "Solo/Duo" | "5v5 Flex";
export type RegionType =
  | "North America"
  | "Europe West"
  | "Europe Nordic & East"
  | "Korea"
  | "Brazil"
  | "Latin America North"
  | "Latin America South"
  | "Oceania"
  | "Turkey"
  | "Russia"
  | "Japan";
